name: Compile primepwn
on: [push]
jobs:
  primepwn-linux:
    strategy:
      matrix:
        arch:
          - runner: ubuntu-22.04
            name: x86_64
          - runner: ubuntu-22.04-arm
            name: aarch64

    name: linux-${{ matrix.arch.name }}
    runs-on: ${{ matrix.arch.runner }}

    steps:
      - uses: actions/checkout@v6

      - name: Run compile script
        run: ./compile.sh

      - name: Zip primepwn
        run: zip -r primepwn_linux-${{ matrix.arch.name }}.zip primepwn

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: primepwn_linux-${{ matrix.arch.name }}.zip
          path: primepwn_linux-${{ matrix.arch.name }}.zip
